MODEL:
  NAME: 'ViT-B-16'
  STRIDE_SIZE: [16, 16]
  NECK: 'bnneck'
  COS_LAYER: false
  SIE_CAMERA: false
  SIE_VIEW: false
  DEVICE_ID: "0"

INPUT:
  SIZE_TRAIN: [224, 224]
  SIZE_TEST: [224, 224]
  PROB: 0.5 # random horizontal flip prob
  PADDING: 10
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]

DATASETS:
  NAMES: 'disfa'
  ROOT_DIR: 'Face_DATA'

DATALOADER:
  SAMPLER: 'softmax'
  NUM_INSTANCE: 4
  NUM_WORKERS: 4

SOLVER:
  OPTIMIZER_NAME: 'Adam'
  SEED: 42
  IMS_PER_BATCH: 32
  CHECKPOINT_PERIOD: 5
  LOG_PERIOD: 50
  EVAL_PERIOD: 1
  
  # Stage 1: Frozen Backbone (10 Epochs)
  STAGE1:
    MAX_EPOCHS: 20
    BASE_LR: 0.0001
    OPTIMIZER_NAME: 'Adam'
    WEIGHT_DECAY: 0.0005
    WEIGHT_DECAY_BIAS: 0.0005
    WARMUP_ITERS: 500
    WARMUP_METHOD: 'linear'
    WARMUP_FACTOR: 0.01
    EVAL_PERIOD: 1
    LOG_PERIOD: 50

  # Stage 2: LoRA Fine-tuning (20 Epochs)
  STAGE2:
    MAX_EPOCHS: 30
    BASE_LR: 0.00005
    OPTIMIZER_NAME: 'Adam'
    WEIGHT_DECAY: 0.0005
    WEIGHT_DECAY_BIAS: 0.0005
    STEPS: [15, 25]
    GAMMA: 0.5
    WARMUP_ITERS: 500
    WARMUP_METHOD: 'linear'
    WARMUP_FACTOR: 0.01
    EVAL_PERIOD: 1
    LOG_PERIOD: 50
    LARGE_FC_LR: True
    ATTN_PENALTY_WEIGHT: 20.0

TEST:
  IMS_PER_BATCH: 64
  RE_RANKING: false
  WEIGHT: '' # path to trained model
  NECK_FEAT: 'after'
  FEAT_NORM: 'yes'

OUTPUT_DIR: 'logs/au_vit_base'
