MODEL:
  NAME: 'ViT-B-16'
  STRIDE_SIZE: [16, 16]
  NECK: 'bnneck'
  COS_LAYER: false
  SIE_CAMERA: false
  SIE_VIEW: false
  DEVICE_ID: "0"

INPUT:
  SIZE_TRAIN: [224, 224]
  SIZE_TEST: [224, 224]
  PROB: 0.5 # random horizontal flip prob
  PADDING: 10
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]

DATASETS:
  NAMES: 'disfa'
  ROOT_DIR: 'AUs_DATA'

DATALOADER:
  SAMPLER: 'softmax'
  NUM_INSTANCE: 4
  NUM_WORKERS: 4

SOLVER:
  OPTIMIZER_NAME: 'Adam'
  BASE_LR: 0.00035
  WARMUP_METHOD: 'linear'
  WARMUP_ITERS: 2000
  WARMUP_FACTOR: 0.01
  STEPS: [40, 70]
  GAMMA: 0.1
  MAX_EPOCHS: 30
  IMS_PER_BATCH: 32
  CENTER_LOSS_WEIGHT: 0.0005
  CENTER_LR: 0.5
  CHECKPOINT_PERIOD: 5
  LOG_PERIOD: 50
  EVAL_PERIOD: 1
  SEED: 42

TEST:
  IMS_PER_BATCH: 64
  RE_RANKING: false
  WEIGHT: '' # path to trained model
  NECK_FEAT: 'after'
  FEAT_NORM: 'yes'

OUTPUT_DIR: 'logs/au_vit_base'
